# Generated by Django 2.0.7 on 2018-09-08 16:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
                ('comment', models.TextField(blank=True)),
                ('date_of_creatin', models.DateTimeField(auto_now_add=True)),
                ('examiner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Без названия', help_text='Введите название задачи', max_length=100)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('image_attached', models.ImageField(blank=True, null=True, upload_to='images_to_problems')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['date_of_creation'],
            },
        ),
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('problems_solved', models.TextField(blank=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('image_attached', models.ImageField(blank=True, null=True, upload_to='images_to_solutions')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.Problem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.ProfileData')),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
                'ordering': ['date_of_creation'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип задачи', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='type_of_problem',
            field=models.ManyToManyField(to='archive.TypeOfProblem'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='solution',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='archive.Solution'),
        ),
    ]
