# Generated by Django 2.0.7 on 2018-10-11 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_profiledata_favourite_problem_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='date_of_creatin',
            new_name='date_of_creation',
        ),
    ]
