# Generated by Django 2.0.7 on 2018-10-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20181011_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='solutions_sent',
            field=models.TextField(blank=True),
        ),
    ]
