# Generated by Django 2.0.7 on 2018-10-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_profiledata_solutions_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledata',
            name='solutions_sent',
        ),
    ]
