# Generated by Django 2.0.7 on 2018-10-13 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_remove_profiledata_solutions_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluation',
            options={'ordering': ['date_of_creation'], 'permissions': (('can_assess', 'Assess solution'),), 'verbose_name': 'Оценивание', 'verbose_name_plural': 'Оценивания'},
        ),
    ]
